name: Web UI Automation Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-automation-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
     # setup browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.4.0

    # setup gradle
    - name: Setup Gradle
      run: chmod +x gradlew

    # execute test script
    - name: Execute Test
      run: ./gradlew cucumber

    # upload artifact
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: Cucumber_Reports
        path: reports
        retention-days: 5
